### ISSUE TITLE
The best model's 

### ISSUE THREAD

**Issue by Haitons** [agadetsky/pytorch-definitions#3]
Hello， I want to reproduce your experiment. Can you share parameters of your best model S+I-Adaptive and S+I-Attention？

**Comment by eryaw** [comment]
Hi

I am also working on reproducing your experiment. Could you share the parameters settings of your best S+I-Adaptive and S+I-Attention (including the parameters for training Adagram vectors) as well, to [eryaw@student.unimelb.edu.au](url)?

Thanks !
